version: "2"
linters:
  default: all
  disable:
    - arangolint
    - cyclop
    - ginkgolinter
    - promlinter
    - protogetter
    - spancheck
    - testableexamples
    - testifylint
    - testpackage
    - zerologlint
    - wsl
    - wsl5
formatters:
  enable:
    - gci
    - gofmt
    - goimports
    - golines
