---
services:
  mneme-server:
    container_name: mneme-server
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - 4444:4444
    environment:
      - DATABASE_URL=postgres://postgres:password@mneme-postgres:5432/postgres
    depends_on:
      - db

  mneme-postgres:
    image: postgres:17
    container_name: mneme-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    # volumes:
    #   - /var/lib/postgresql/data
