---
services:
  server:
    container_name: mneme-server
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - 4444:4444
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: mneme-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    # volumes:
    #   - /var/lib/postgresql/data
